In [24]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
np.set_printoptions(precision=4)

In [123]:
def entropy(data):
    data=np.array(data)
    classes=np.unique(data)
    
    m=len(data)
    n=len(classes)
    if n<=1:return 0
    
    #cool part,I dont using for loop
    data.shape=(-1,1)
    classes.shape=(1,-1)
    
    dc=(data==classes) #mxn
    distribution=np.sum(dc,axis=0)/m
    
    _entropy=np.sum(distribution*(np.log(1/distribution)))
    return _entropy
def cond_entropy(y1,y2):
    entropy_y1=entropy(y1)
    entropy_y2=entropy(y2)
    m1,m2=len(y1),len(y2)
    m=m1+m2
    return (m1/m)*entropy_y1+(m2/m)*entropy_y2

# def feature_select(x,y):
#     print('original entropy ',entropy(y))
#     I=[]
#     for i in range(len(x)):
#         t=x[i]
#         I.append(cond_entropy(y[x<=t],y[x>t]))
#     index=np.argmin(I)
#     print('entropy after feature select')
#     print(np.array(I))
#     return x[index]
def feature_select(x,y):
    print('original entropy ',entropy(y))
    asc_index=np.argsort(x)
    x=x[asc_index]
    y=y[asc_index]
    
    diff=np.diff(y,n=1)
    tindex=np.where(diff!=0)[0]
    thresolds=x[tindex]

    
    x.shape=(-1,1)
    thresolds.shape=(1,-1)
     
    
    #cool part
    dc=x<=thresolds
    m,t=dc.shape
    I=[]
    for i in range(t):
        mask=dc[:,i]
        I.append(cond_entropy(y[mask],y[~mask]))
    index=np.argmin(I)
    
    print('entropy after feature select')
    print(np.array(I))
    x.shape=(-1,)
    return x[tindex[index]]

In [120]:
x=np.arange(10)
y=np.array([1,1,1,-1,-1,-1,1,1,1,-1])

In [122]:
feature_select(x,y)
print(y)

original entropy  0.6730116670092565
entropy after feature select
[0.6183 0.5545 0.478  0.6408 0.673  0.6408 0.669  0.6679 0.5729 0.673 ]
[ 1  1  1 -1 -1 -1  1  1  1 -1]


In [44]:
arr=np.array([1,1,1,134,45,3,46,45,65,3,23424,234,12,12,3,546,1,2])
print(np.where(arr!=3))

(array([ 0,  1,  2,  3,  4,  6,  7,  8, 10, 11, 12, 13, 15, 16, 17]),)


In [48]:
a=np.array([True,False])

In [49]:
a


array([ True, False])

In [52]:
~ a

array([False,  True])