In [1]:
import numpy as np
import torch

## more about tensor

In [26]:
#show clap,float,long,narrow,ndimension
X=torch.rand((5,3))*6
print(X.data)
print(X.clamp(min=0.2,max=0.3))
print(X.float())
print(X.long()) #floor operation
print(X.size(0),X.size(1),X.ndimension())
print(X[0:1,0:1])
print(X.narrow(1,1,2))

tensor([[5.9778, 4.3964, 2.7921],
        [0.9371, 3.1909, 3.9492],
        [1.4180, 5.1711, 4.9819],
        [5.5627, 5.2827, 3.7189],
        [0.2117, 0.2405, 3.7115]])
tensor([[0.3000, 0.3000, 0.3000],
        [0.3000, 0.3000, 0.3000],
        [0.3000, 0.3000, 0.3000],
        [0.3000, 0.3000, 0.3000],
        [0.2117, 0.2405, 0.3000]])
tensor([[5.9778, 4.3964, 2.7921],
        [0.9371, 3.1909, 3.9492],
        [1.4180, 5.1711, 4.9819],
        [5.5627, 5.2827, 3.7189],
        [0.2117, 0.2405, 3.7115]])
tensor([[5, 4, 2],
        [0, 3, 3],
        [1, 5, 4],
        [5, 5, 3],
        [0, 0, 3]])
5 3 2
tensor([[5.9778]])
tensor([[4.3964, 2.7921],
        [3.1909, 3.9492],
        [5.1711, 4.9819],
        [5.2827, 3.7189],
        [0.2405, 3.7115]])


In [35]:
##math operation!!
X=torch.rand(10,3)
Y=torch.rand(3,4)
print(torch.matmul(X,Y).size())#or mm for short
Z=torch.rand(10,3)
cat=torch.cat((X,Z),dim=1)
print(cat.size())
stack=torch.stack([X,Z],dim=1)
print(stack.size())

torch.Size([10, 4])
torch.Size([10, 6])
torch.Size([10, 2, 3])


In [42]:
#clone
X=torch.rand(3)
Y=X.data.clone()
X[0]=1
print(X)
print(Y)
print(X.new().int().dtype)
print(X.requires_grad)

tensor([1.0000, 0.2387, 0.4896])
tensor([0.0865, 0.2387, 0.4896])
torch.int32
False


In [43]:
X=torch.ones((3,2),requires_grad=True) #要设置参数才有倒数
Y=torch.sum(X,dim=1)
Z=torch.sum(Y)

In [46]:
Z.backward()

In [51]:
X.grad

tensor([[2., 2.],
        [2., 2.],
        [2., 2.]])

In [33]:
x = torch.randn(3, requires_grad=True)
with torch.no_grad():
    y = x * 2
print(y.requires_grad)
while y.data.norm() < 1000:
    y = y * 2

print(y.requires_grad)

False
False


In [30]:
torch.norm(y/2)

tensor(720.4920, grad_fn=<NormBackward0>)

In [70]:
#do a complex example:
def roi():
    X=torch.rand(5,5,requires_grad=True)
    Y=X[1:4,1:4]
    print(Y)
    Y.backward(Y)
#     Z=torch.sum(Y)
#     Z.backward(gradient=torch.Tensor([99]))
    print(X.grad)
roi()

tensor([[0.6672, 0.4121, 0.8875],
        [0.4778, 0.2725, 0.7174],
        [0.7872, 0.7957, 0.1605]], grad_fn=<SliceBackward>)
tensor([[0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.6672, 0.4121, 0.8875, 0.0000],
        [0.0000, 0.4778, 0.2725, 0.7174, 0.0000],
        [0.0000, 0.7872, 0.7957, 0.1605, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000, 0.0000]])
