In [2]:
import numpy as np
import torch

- 1.Basic Function to Create Tensor
 - rand,zeros,rand_like
- 2.property of Tensor
 - size() dtype
- 3.convert between numpy and torch
 - tensor.numpy()
 - torch.from_numpy()

1.Basic Function to Create Tensor
------------------------
- A.rand,zeros
- B.rand_like,new_ones

In [15]:
X1=torch.rand(3,2)
print(X1)
X2=torch.tensor([1.0,2,3])
print(X2)
X3=torch.rand_like(X2)
print(X3)
X4=X3.new_ones(2,2)
print(X4)
X5=torch.zeros(2,3)
print(X5)
print('------------------')

tensor([[0.0364, 0.4059],
        [0.5362, 0.2326],
        [0.2987, 0.1356]])
tensor([1., 2., 3.])
tensor([0.0753, 0.6292, 0.7714])
tensor([[1., 1.],
        [1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
------------------


2.property of Tensor
--------------------------------------

In [23]:
X1=torch.Tensor([1,2,3])
X1=X1.type(torch.uint8)
print(X1.size(),X1.dtype)

torch.Size([3]) torch.uint8


In [20]:
#operation

In [22]:
A=torch.rand(3,2)
print(A)
B=torch.rand(1,2)
print(B)
A+B

tensor([[0.4536, 0.8339],
        [0.9747, 0.0692],
        [0.4857, 0.6335]])
tensor([[0.8960, 0.1444]])


tensor([[1.3496, 0.9784],
        [1.8706, 0.2137],
        [1.3817, 0.7780]])

In [38]:
A=torch.arange(0,9)
A=A.view(3,3)
B=A

In [43]:
B[:,:]=0

In [44]:
A

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [53]:
B.add_(22)

tensor([[66, 66, 66],
        [66, 66, 66],
        [66, 66, 66]])

In [51]:
C=B.numpy()

In [54]:
C

array([[66, 66, 66],
       [66, 66, 66],
       [66, 66, 66]])

In [55]:
T=np.random.randn(2,3,4)
T=torch.from_numpy(T)

In [58]:
print(torch.abs(T))

tensor([[[0.9383, 0.7436, 0.0240, 1.6050],
         [0.1897, 0.6814, 0.1022, 1.1948],
         [1.2908, 0.0459, 0.3254, 2.4225]],

        [[0.3525, 0.3212, 0.6038, 0.5200],
         [1.2822, 0.0849, 1.6280, 0.3315],
         [0.5339, 0.9847, 1.9291, 0.6901]]], dtype=torch.float64)


In [57]:
A

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])