In [1]:
import numpy as np
import torch

In [5]:
X=torch.zeros((3,2))
print(X[:,0:1].size())

torch.Size([3, 1])


In [7]:
X=torch.rand(3,2)
print(X)

tensor([[0.6894, 0.9883],
        [0.3425, 0.0918],
        [0.1344, 0.4281]])


In [14]:
X=torch.tensor([1,2.3])
print(X.dtype)

torch.float32


In [15]:
X.new_ones(3,2)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [16]:
torch.rand_like(X)

tensor([0.6513, 0.8755])

In [18]:
shape=X.size()
print(shape)

torch.Size([2])


In [19]:
shape[0]

2

In [20]:
#operation

In [22]:
A=torch.rand(3,2)
print(A)
B=torch.rand(1,2)
print(B)
A+B

tensor([[0.4536, 0.8339],
        [0.9747, 0.0692],
        [0.4857, 0.6335]])
tensor([[0.8960, 0.1444]])


tensor([[1.3496, 0.9784],
        [1.8706, 0.2137],
        [1.3817, 0.7780]])

In [38]:
A=torch.arange(0,9)
A=A.view(3,3)
B=A

In [43]:
B[:,:]=0

In [44]:
A

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [53]:
B.add_(22)

tensor([[66, 66, 66],
        [66, 66, 66],
        [66, 66, 66]])

In [51]:
C=B.numpy()

In [54]:
C

array([[66, 66, 66],
       [66, 66, 66],
       [66, 66, 66]])

In [55]:
T=np.random.randn(2,3,4)
T=torch.from_numpy(T)

In [58]:
print(torch.abs(T))

tensor([[[0.9383, 0.7436, 0.0240, 1.6050],
         [0.1897, 0.6814, 0.1022, 1.1948],
         [1.2908, 0.0459, 0.3254, 2.4225]],

        [[0.3525, 0.3212, 0.6038, 0.5200],
         [1.2822, 0.0849, 1.6280, 0.3315],
         [0.5339, 0.9847, 1.9291, 0.6901]]], dtype=torch.float64)


In [57]:
A

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])