# First review the base knowage of linear Algebra

<a href="https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.linalg.eig.html">eig</a> 

In [1]:
import numpy as np

In [2]:
np.random.seed(0)
A=np.random.rand(5,5)*5;
print(A)
print("------------------")
W,S=np.linalg.eig(A)
S_inv=np.linalg.inv(S)
B=S.dot(np.diag(W)).dot(S_inv)
print(B.real)

[[2.74406752 3.57594683 3.01381688 2.72441591 2.118274  ]
 [3.22947057 2.18793606 4.458865   4.8183138  1.91720759]
 [3.95862519 2.6444746  2.84022281 4.62798319 0.35518029]
 [0.4356465  0.10109199 4.16309923 3.89078375 4.35006074]
 [4.89309171 3.99579282 2.30739681 3.90264588 0.59137213]]
------------------
[[2.74406752 3.57594683 3.01381688 2.72441591 2.118274  ]
 [3.22947057 2.18793606 4.458865   4.8183138  1.91720759]
 [3.95862519 2.6444746  2.84022281 4.62798319 0.35518029]
 [0.4356465  0.10109199 4.16309923 3.89078375 4.35006074]
 [4.89309171 3.99579282 2.30739681 3.90264588 0.59137213]]


# next we implement PR algrithm
formula: pr_new=(1-d)/n+d* (W*pr_old) <br />
d is prob that a user keep stay at remain sites(prob a given vertex jump to another vertex)<br />
W[i][j]=I{j-->i}/degree(j)

In [3]:
def PR(W,prob=0.85,t=10):
    '''
        W:relation matrix,wij=I[j->i] / degree(j)
        prob:prob jump from one to another vertex
        t:number of iteration
        return:rank,rank score,decent order
    '''
    
    n=W.shape[0]
    #initial uniformly
    init_score=np.ones(n)/n
    
    E,S=np.linalg.eig(W)
    S_inv=np.linalg.inv(S)
    
    #resolve or project initial score to eig space S
    resolve=S_inv.dot(init_score)
    
    score=np.real(S.dot(np.diag(E**t)).dot(resolve))
    score=prob*score+(1-prob)/n
    
    
    rank=np.argsort(-score)
    rankScore=score[rank]
    return rank,rankScore

### example from this video <a href='https://www.youtube.com/watch?v=P8Kt6Abq_rM'>video</a> 

In [4]:
W=np.array([
        [0,0,1/3,0],
        [1/2,0,1/3,0],
        [1/2,0,0,1],
        [0,1,1/3,0]
    ])
PR(W,prob=1,t=99)

(array([2, 3, 1, 0]), array([0.375 , 0.3125, 0.1875, 0.125 ]))

## Now review some NLTK 
## TOKENIZE
## Corpara: body of text
## Lexicon:the mean of word

In [5]:
from nltk import sent_tokenize,word_tokenize
#unfortunally this fail to tokenize chinere,using jieba instead
import jieba

ImportError: No module named 'nltk'

In [6]:
msg="黄晓明工作室对此发声明否认，称黄晓明不认识高某，未参与过任何操纵股票的行为；黄晓明未曾受过任何与股票有关的处罚，亦未介入过任何与股票有关的调查。黄晓明工作室还敦促相关方即刻删撤一切虚假信息，以免对公众造成误导并导致己方法律责任的承担。返回搜狐"

In [7]:
list(jieba.cut(msg,cut_all=False))

NameError: name 'jieba' is not defined

In [8]:
import jieba.posseg as pseg

In [9]:
words=[]
for char,pos in pseg.cut(msg):
#     if pos.startswith('n') or pos.startswith('a'):
    print('word %s,pos:%s'%(char,pos))
#         words.append(char)
words=set(words)

Building prefix dict from the default dictionary ...
DEBUG:jieba:Building prefix dict from the default dictionary ...
Dumping model to file cache /tmp/jieba.cache
DEBUG:jieba:Dumping model to file cache /tmp/jieba.cache
Loading model cost 1.509 seconds.
DEBUG:jieba:Loading model cost 1.509 seconds.
Prefix dict has been built succesfully.
DEBUG:jieba:Prefix dict has been built succesfully.


word 黄晓明,pos:nr
word 工作室,pos:n
word 对此,pos:d
word 发声明,pos:l
word 否认,pos:v
word ，,pos:x
word 称,pos:v
word 黄晓明,pos:nr
word 不,pos:d
word 认识,pos:v
word 高某,pos:nr
word ，,pos:x
word 未,pos:d
word 参与,pos:v
word 过,pos:ug
word 任何,pos:r
word 操纵,pos:v
word 股票,pos:n
word 的,pos:uj
word 行为,pos:v
word ；,pos:x
word 黄晓明,pos:nr
word 未曾,pos:d
word 受过,pos:v
word 任何,pos:r
word 与,pos:p
word 股票,pos:n
word 有关,pos:vn
word 的,pos:uj
word 处罚,pos:v
word ，,pos:x
word 亦,pos:d
word 未,pos:d
word 介入,pos:v
word 过,pos:ug
word 任何,pos:r
word 与,pos:p
word 股票,pos:n
word 有关,pos:vn
word 的,pos:uj
word 调查,pos:vn
word 。,pos:x
word 黄晓明,pos:nr
word 工作室,pos:n
word 还,pos:d
word 敦促,pos:v
word 相关,pos:v
word 方,pos:n
word 即刻,pos:d
word 删撤,pos:v
word 一切,pos:r
word 虚假,pos:a
word 信息,pos:n
word ，,pos:x
word 以免,pos:c
word 对,pos:p
word 公众,pos:n
word 造成,pos:v
word 误导,pos:n
word 并,pos:c
word 导致,pos:v
word 己方,pos:n
word 法律责任,pos:n
word 的,pos:uj
word 承担,pos:v
word 。,pos:x
word 返回,pos:v
word 搜狐,pos:nz


# some document about jieba <a href='https://github.com/fxsjy/jieba'>doc</a>

In [10]:
def corpora2Sentence(corpos):
    '''
        cut corpos into sentences
        return:
            sentences:list,one element represent a none adj,select[i]=(word,pos) mean word as pos
            vocabs:a set of all words occur in corpos
            word_idx and idx_word:the map between idx and vocab,I using a matrix representation
                for the graph
            vocabs_position:a dict,the element look like: 
                V(i):[p1,p2,..pn],mean word V occur at positon p1,p2,..pn
            position_vocabs:reverse of vocabs_position:
                pi:V(j),mean at positon pi is word V(j)
    '''
    sentences=[]
    vocabs=[]  #store all vocabulary
    vocabs_position={}
    word_idx=0 #the word position at corpos
    for char,pos in pseg.cut(corpos):
        word_idx+=1
        if pos=='x':continue
        elif (pos.startswith('n') or pos=='a' or pos.startswith('v'))and len(char)>1:
            sentences.append((char,word_idx))
            vocabs.append(char)
            if char in vocabs_position:vlist=vocabs_position[char]
            else:
                vlist=[]
                vocabs_position[char]=vlist
            vlist.append(word_idx)
        
        
    vocabs=set(vocabs)
    word_idx={c:i for i,c in enumerate(vocabs)}
    idx_word={i:c for i,c in enumerate(vocabs)}
    
    position_vocabs={}
    for vocb,poslist in vocabs_position.items():
        for p in poslist:position_vocabs[p]=vocb

    return sentences,vocabs,word_idx,idx_word,vocabs_position,position_vocabs

## Now I need a little Graph Theory to handle the output

In [ ]:
#[产品]-[]
#[信息化]-[]
#[商用车]-[]
#[工业]-[]
#[新能源]-[汽车,船舶]
#[汽车]-[产品,标准]
#[船舶]-[标准]
#[标准]-[]
#[目录]-[]
#[车船税]-[]
#output should be  信息化 商用车 工业 新能源-汽车-产品 新能源-汽车-标准 新能源-船舶-标准 目录 车船税

In [11]:
class Vertex():
    '''
        I using adjacency list representations,a convinient way to do DFS
    
    '''
    def __init__(self,w):
        self.content=w
        self.inDegree=0
        self.adj=set() #adjacentcy vertexs
    def __eq__(self,other):
        return self.content==other.content
    def __repr__(self):
        return self.content
    def __str__(self):
        return self.__repr__()
    def __hash__(self):
        return hash(self.content)
class Vsets():
    def __init__(self,words):
        '''
            maintain a set contain all the vertex
        '''
        self.vertexes={w:Vertex(w) for w in words}
    def connect(self,v1,v2):
        '''
            add a edge from v1->v2
            v1,v2 are string(key of self.vertexes)
        '''
        v1=self.vertexes[v1]
        v2=self.vertexes[v2]
        v1.adj.add(v2)
        v2.inDegree+=1
    def DFS(self):
        '''
            Do Depth First Serch on vertexes,start point is all vertex that
            have inDegree of 0,in a other word,it's the root of tree
            
            return: a list of all the possible combination of content from root to leaf
        '''
        
        #a helper dict member all visited vertex,initial state:no one be visited
        self.visited={}
        #record all vertex have in degress 0
        root=set()
        for w,v in self.vertexes.items():
            self.visited[v]=False
            if v.inDegree==0:
                root.add(v)
                
                
        
        ret=[]
        #do DFS_visit from root
        for v in root:
            v_list=self.DFS_Visit(v)
            ret.extend(v_list)
        del self.visited
        return ret
    def DFS_Visit(self,s):
        '''
            start from s,DFS to leaf
            return: a list of all the possible combination of content from s to it's leaf
        '''
        self.visited[s]=True #first label this a visited vertex
        ret=[]
        
        
        for u in s.adj:
            if self.visited[u]==False:
                u_list=self.DFS_Visit(u)  #a list of all possible from u,do DFS_VISIT
            else:
                u_list=self.visited[u] #no need search 
            #append prefix s.content to subTree
            ret.extend([s.content+'-'+c for c in u_list])
        
        #if s have no subTree to visited
        if len(ret)==0:ret.append(s.content)
        self.visited[s]=ret
        return sorted(ret)
#[产品]-[]
#[信息化]-[]
#[商用车]-[]
#[工业]-[]
#[新能源]-[汽车,船舶]
#[汽车]-[产品,标准]
#[船舶]-[标准]
#[标准]-[]
#[目录]-[]
#[车船税]-[]
#output should be  信息化 商用车 工业 目录 车船税 新能源-汽车-产品 新能源-汽车-标准 新能源-船舶-标准 

vset=Vsets(['产品','信息化','商用车','工业','新能源','汽车','船舶','标准','目录','车船税'])
vset.connect('新能源','汽车')
vset.connect('新能源','船舶')
vset.connect('汽车','产品')
vset.connect('汽车','标准')
vset.connect('船舶','标准')
# vset.connect('新能源','汽车')
print(vset.DFS())

['商用车', '信息化', '车船税', '目录', '工业', '新能源-汽车-产品', '新能源-汽车-标准', '新能源-船舶-标准']


# Construct Sequence Graph Model

In [12]:
class Graph():
    def __init__(self,filename):
        '''
        
        '''
        #cut corpus to words,remain only none and adjective
        with open(filename) as f:
            corpora=f.read()
            self.sentence,self.vocab,self.word_idx,self.idx_word,self.vocabs_position,self.position_vocabs=corpora2Sentence(corpora)
        
        self.words=len(self.vocab)
        self.H=np.zeros((self.words,self.words)) #matrix representation
        
    def _connect(self,char1,char2):
        '''
            char1,char2 is select 2 words by jieba,
            char2 is after char2,
            if the distance between char1,char2 is less than window_size,
            I treat this is a valid edge,then update graph matrix
            
            char1:tuple(word1,position1)
            
            return True/False
        '''
        c1,p1,c2,p2=*char1,*char2
        
        if(abs(p2-p1)>self.windowSize):return False
        idx1,idx2=self.word_idx[c1],self.word_idx[c2]
        if idx1!=idx2:self.H[idx1,idx2]=self.H[idx2,idx1]=1
        return True
    def getMatrix(self,windowSize=5,eps=1e-6):
        '''
            compute graph matrix,using by Page Rank 
            windowsSize: within windowsSize ragime of word s view as neibourhood of s
        '''
        self.windowSize=windowSize
        
        sentencelen=len(self.sentence)
        for i in range(sentencelen):
            char1=self.sentence[i]
            for j in range(i+1,sentencelen):
                char2=self.sentence[j]
                if self._connect(char1,char2)==False:break
        
        degree=np.sum(self.H,axis=0)
        degree[degree==0]=eps
        H=self.H/degree
        return H
    def rank(self,indices,top=1000):
        '''
            indices:the word's index according to Page Rank Algrithm,in decent order
            top:select first top word of indices
        '''

        
        selectedWords=[]
        for i in range(min(len(indices),top)):
            selectedWords.append(self.idx_word[indices[i]])
        #using graph tool to handle the output
        vstool=Vsets(selectedWords)
        
        #sort all positon of selected word occur in corpos
        sel_pos_list=[]
        for w in selectedWords:
            sel_pos_list.extend(self.vocabs_position[w])
        #sel_pos_list is a list of selectWords's positon ,for example,个税 is a select word,
        #occur at position 10,30(reference to corpos),sel_pos_list look like [....10...30.....]
        sel_pos_list=sorted(sel_pos_list) 
        
        
        '''
            no go through sel_pos_list, if sel_pos_list[i] sel_pos_list[i+1] are continue posion ,
            that mean W[sel_pos_list[i]] and W[sel_pos_list[i+1]] should merged as one word,
            with vstool to add a edge from  W[sel_pos_list[i]] to W[sel_pos_list[i+1]],
            vstool can handle consitive word properly!
        
        '''
        for i in range(len(sel_pos_list)-1):
            pi=sel_pos_list[i]
            Wi=self.position_vocabs[pi]
            pj=sel_pos_list[i+1]
            Wj=self.position_vocabs[pj]
            if(pj-pi==1 and Wi !=Wj):
                vstool.connect(Wi,Wj)
        ret=vstool.DFS()
        return ret,selectedWords

In [25]:
graph=Graph('PR/tx2.txt')

In [28]:
!cat 'PR/tx2.txt'

根据国务院有关部署，现就调整房地产交易环节契税、营业税优惠政策通知如下：

　　一、关于契税政策

　　（一）对个人购买家庭唯一住房（家庭成员范围包括购房人、配偶以及未成年子女，下同），面积为90平方米及以下的，减按1%的税率征收契税；面积为90平方米以上的，减按1.5%的税率征收契税。

　　（二）对个人购买家庭第二套改善性住房，面积为90平方米及以下的，减按1%的税率征收契税；面积为90平方米以上的，减按2%的税率征收契税。

　　家庭第二套改善性住房是指已拥有一套住房的家庭，购买的家庭第二套住房。

　　（三）纳税人申请享受税收优惠的，根据纳税人的申请或授权，由购房所在地的房地产主管部门出具纳税人家庭住房情况书面查询结果，并将查询结果和相关住房信息及时传递给税务机关。暂不具备查询条件而不能提供家庭住房查询结果的，纳税人应向税务机关提交家庭住房实有套数书面诚信保证，诚信保证不实的，属于虚假纳税申报，按照《中华人民共和国税收征收管理法》的有关规定处理，并将不诚信记录纳入个人征信系统。

　　按照便民、高效原则，房地产主管部门应按规定及时出具纳税人家庭住房情况书面查询结果，税务机关应对纳税人提出的税收优惠申请限时办结。

　　（四）具体操作办法由各省、自治区、直辖市财政、税务、房地产主管部门共同制定。

　　二、关于营业税政策

　　个人将购买不足2年的住房对外销售的，全额征收营业税；个人将购买2年以上（含2年）的住房对外销售的，免征营业税。

　　办理免税的具体程序、购买房屋的时间、开具发票、非购买形式取得住房行为及其他相关税收管理规定，按照《国务院办公厅转发建设部等部门关于做好稳定住房价格工作意见的通知》（国办发〔2005〕26号）、《国家税务总局 财政部 建设部关于加强房地产税收管理的通知》（国税发〔2005〕89号）和《国家税务总局关于房地产税收政策执行中几个具体问题的通知》（国税发〔2005〕172号）的有关规定执行。

　　三、关于实施范围

　　北京市、上海市、广州市、深圳市暂不实施本通知第一条第二项契税优惠政策及第二条营业税优惠政策，上述城市个人住房转让营业税政策仍按照《财政部 国家税务总局关于调整个人住房转让营业税政策的通知》（财税〔2015〕39号）执行。

　　上述城市以外的其他地区适用本通知全部规定。

In [26]:
H=graph.getMatrix(10)
print(graph.vocab)

{'减按', '政策', '拥有', '提出', '实施', '中华人民共和国', '应对', '办法', '上海市', '购买', '住房价格', '家庭成员', '执行', '套数', '属于', '提交', '情况', '部门', '发票', '纳入', '深圳市', '纳税', '子女', '个人', '城市', '北京市', '限时', '形式', '家庭', '调整', '建设部', '通知', '程序', '房屋', '保证', '处理', '广州市', '面积', '授权', '诚信', '自治区', '优惠', '征收', '税收', '相关', '具体', '行为', '原则', '具备', '提供', '财政', '财税', '高效', '包括', '国家税务总局', '不能', '书面', '征信', '直辖市', '不实', '契税', '规定', '查询', '纳税人', '税收管理', '办理', '管理法', '稳定', '全部', '范围', '住房', '记录', '交易', '意见', '配偶', '地区', '部署', '制定', '销售', '税务机关', '环节', '转发', '传递', '做好', '申报', '税率', '便民', '改善', '购房人', '税务', '结果', '国务院办公厅', '工作', '有关', '个人住房', '出具', '所在地', '系统', '不足', '购房', '加强', '国务院', '虚假', '取得', '税收政策', '实有', '问题', '适用', '免税', '时间', '主管部门', '下同', '优惠政策', '享受', '财政部', '信息', '申请', '开具', '免征', '全额', '营业税', '办结', '转让', '条件'}


In [27]:
rank,rankScore=PR(H)
print(rankScore[0:10])
a,b=graph.rank(rank,10)
print(b)
print(a)
# print(rankScore)
#['产品', '信息化', '商用车', '工业', '新能源', '标准', '汽车', '目录', '船舶', '车船税']

[0.03144024 0.02204758 0.02075831 0.01836667 0.01787745 0.01716029
 0.0164818  0.01538152 0.01494893 0.01478611]
['住房', '家庭', '通知', '购买', '规定', '营业税', '纳税人', '税务机关', '个人', '契税']
['税务机关', '营业税', '通知', '个人-购买-家庭-住房', '规定', '纳税人-家庭-住房', '契税']
