In [2]:
#安裝指針
# https://mxnet.apache.org/versions/master/install/ubuntu_setup.html#install-mxnet-for-python
from mxnet import nd

## 1 数组基本操作

In [8]:
x=nd.random.randn(3,2)
y=nd.random.randn(3,2)

In [9]:
nd.dot(x,y.T)


[[-0.27764577 -1.3921164  -1.1867933 ]
 [-0.7567489  -1.7102137  -1.2783389 ]
 [ 0.19005555  2.2632709   2.0424016 ]]
<NDArray 3x3 @cpu(0)>

In [10]:
nd.dot(x.T,y)


[[-1.1098357   0.64698356]
 [ 0.3517933   1.1643778 ]]
<NDArray 2x2 @cpu(0)>

In [14]:
print(x)
print(x[:,0])


[[ 0.6862904   0.35496104]
 [ 1.0731696   0.12017461]
 [-0.9711102  -0.77569664]]
<NDArray 3x2 @cpu(0)>

[ 0.6862904  1.0731696 -0.9711102]
<NDArray 3 @cpu(0)>


In [16]:
x[:,0]=22
print(x)


[[22.          0.35496104]
 [22.          0.12017461]
 [22.         -0.77569664]]
<NDArray 3x2 @cpu(0)>


In [20]:
# 广播
print(x[0])
x+x[0]


[22.          0.35496104]
<NDArray 2 @cpu(0)>



[[44.          0.7099221 ]
 [44.          0.47513565]
 [44.         -0.4207356 ]]
<NDArray 3x2 @cpu(0)>

### 2 与 numpy转换

In [25]:
nx=x.asnumpy()
print(nx,type(nx))

[[22.          0.35496104]
 [22.          0.12017461]
 [22.         -0.77569664]] <class 'numpy.ndarray'>


In [26]:
nd.array(nx)


[[22.          0.35496104]
 [22.          0.12017461]
 [22.         -0.77569664]]
<NDArray 3x2 @cpu(0)>