In [2]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

### 问题:如何把任意一个向量a 旋转到基本坐标轴,找到这样的矩阵?
    我的思路是 
    1.找出与a正交的2个向量b,c,并且把a,b,c都单位化,组成 F=[a,b,c]
    2.F是正交矩阵R=M.T就是我要找的旋转矩阵R
    3.Ra 就把a转到 (1,0,0)的方向,想转会来就用R.T

In [104]:
def localFrames(x):
    '''
    对给出的向量x,找出与x 为第一轴的一组 正交基
    返回
    
    M=[frameX,frameY,frameZ],其中frameX 与x方向一致
    '''
    if isinstance(x,list):x=np.array(x)
        
    y=np.random.randn(3)
    z=np.cross(x,y)
    y=np.cross(z,x)
    
    frameX=(x/np.linalg.norm(x)).ravel()
    frameY=(y/np.linalg.norm(y)).ravel()
    frameZ=(z/np.linalg.norm(z)).ravel()

    M=np.array([frameX,frameY,frameZ])
    return M.T
def RotateMatrix(theta):
    '''
    分别返回绕x,y,z旋转的矩阵
    '''
    c=np.cos(theta)
    s=np.sin(theta)
    
    RX=np.array([[1,0,0],[0,c,-s],[0,s,c]])
    RY=np.array([[c,0,s],[0,1,0],[-s,0,c]])
    RZ=np.array([[c,-s,0],[s,c,0],[0,0,1]])
    return RX,RY,RZ
def rotate(v,point,theta=0):
    '''
    绕v 转转theta
    '''
    if isinstance(point,list):
        point=np.array(point)
        
    #先在v建立正交 基
    RT=localFrames(v)
    R=RT.T
    
    #用把v旋转到x轴的矩阵R旋转point
    p1=R.dot(point)
    #point 绕v旋转 相当于 p1绕x 旋转
    RX,_,_=RotateMatrix(theta)
    
    p2=RX.dot(p1)
    #最后应该旋转回去
    ret=RT.dot(p2)

    return ret

In [105]:
axis=np.array([1,1,1])
print(axis,",norm:",np.linalg.norm(axis))

M=localFrames(axis)
R=M.T
RT=R.T
align_axis=R.dot(axis)
print(align_axis,",norm:",np.linalg.norm(align_axis))
axis=RT.dot(align_axis)
print(axis,",norm:",np.linalg.norm(axis))

[1 1 1] ,norm: 1.7320508075688772
[ 1.73205081e+00  0.00000000e+00 -2.77555756e-17] ,norm: 1.7320508075688776
[1. 1. 1.] ,norm: 1.7320508075688776


In [110]:
axis=np.array([0,0,100])
point=np.array([1,1,0])
rotate(v=axis,point=point,theta=np.pi/2)

array([-1.,  1.,  0.])